.PHONY: all clean compile run

all: compile run

compile:
# $(MAKE) -C big_partition compile
	$(MAKE) -C small_partitions compile
# $(MAKE) -C kamada_kawai compile

run:
# $(MAKE) -C big_partition run
	$(MAKE) -C small_partitions run
# $(MAKE) -C kamada_kawai run

clean:
# $(MAKE) -C big_partition clean
	$(MAKE) -C small_partitions clean
# $(MAKE) -C kamada_kawai clean
